/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditLogs {
  action: string;
  branch_id: number | null;
  created_at: Generated<Timestamp>;
  entity_id: string;
  entity_type: string;
  id: Generated<Int8>;
  meta: Json | null;
  staff_id: number | null;
  staff_role: string | null;
}

export interface Authors {
  archived_at: Timestamp | null;
  archived_by: number | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  normalized_name: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: number | null;
}

export interface BankAccounts {
  account_name: string;
  account_number: string;
  bank_name: string;
  branch_id: number;
  created_at: Generated<Timestamp>;
  currency: string;
  iban: string | null;
  id: Generated<number>;
  is_active: Generated<boolean>;
}

export interface BankReconciliation {
  amount: Numeric;
  bank_account_id: number;
  created_at: Generated<Timestamp>;
  direction: string;
  id: Generated<Int8>;
  notes: string | null;
  payment_ref_id: Int8 | null;
  refund_ref_id: Int8 | null;
  statement_date: Timestamp | null;
  status: Generated<string>;
}

export interface BookAuthors {
  author_id: number;
  book_id: number;
  sort_order: Generated<number>;
}

export interface BookBranchPrices {
  book_id: number;
  branch_id: number;
  edition_id: Generated<number>;
  format_id: Generated<number>;
  price: Numeric;
}

export interface BookCategories {
  book_id: number;
  category_id: number;
}

export interface BookEditHistory {
  book_id: number;
  changed_at: Generated<Timestamp>;
  changed_by: number;
  field_name: string;
  id: Generated<Int8>;
  new_value: string | null;
  old_value: string | null;
}

export interface BookEditions {
  code: string;
  id: Generated<number>;
  label: string;
  sort_order: Generated<number>;
}

export interface BookFormats {
  code: string;
  id: Generated<number>;
  label: string;
  sort_order: Generated<number>;
}

export interface Books {
  archived_at: Timestamp | null;
  archived_by: number | null;
  cover_image_url: string | null;
  created_at: Generated<Timestamp>;
  default_price: Numeric | null;
  description: string | null;
  edition: string | null;
  edition_id: number | null;
  format: string | null;
  format_id: number | null;
  genre: string | null;
  id: Generated<number>;
  is_active: Generated<boolean>;
  isbn: string;
  language: string | null;
  publisher: string | null;
  publisher_id: number | null;
  search_vector: string | null;
  sku: string | null;
  status: Generated<string>;
  title: string;
  trade_value: Numeric | null;
  updated_at: Generated<Timestamp>;
  updated_by: number | null;
}

export interface BookSuppliers {
  book_id: number;
  is_primary: Generated<boolean>;
  supplier_id: number;
  supplier_sku: string | null;
}

export interface BookTags {
  book_id: number;
  tag: string;
}

export interface BranchConfig {
  branch_id: number;
  key: string;
  updated_at: Generated<Timestamp>;
  updated_by: number;
  value: Json;
}

export interface Branches {
  address: string;
  contact_info: Json;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_active: Generated<boolean>;
  name: string;
  operating_hours: Json;
}

export interface Categories {
  archived_at: Timestamp | null;
  archived_by: number | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  normalized_name: string;
  parent_id: number | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: number | null;
}

export interface CustomerGroupMembership {
  customer_id: number;
  group_id: number;
}

export interface CustomerGroups {
  description: string | null;
  discount_pct: Generated<Numeric>;
  id: Generated<number>;
  name: string;
}

export interface Customers {
  address: string | null;
  archived_at: Timestamp | null;
  archived_by: number | null;
  branch_id: number | null;
  city: string | null;
  created_at: Generated<Timestamp>;
  created_by: number | null;
  customer_code: string;
  date_of_birth: Timestamp | null;
  email_encrypted: string | null;
  email_lookup: string | null;
  full_name: string;
  gender: string | null;
  id: Generated<number>;
  is_active: Generated<boolean>;
  phone_encrypted: string | null;
  phone_lookup: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: number | null;
}

export interface ExchangeIncomingItems {
  book_id: number;
  evaluated_unit_price: Numeric;
  exchange_id: Int8;
  id: Generated<Int8>;
  quantity: number;
  total_price: Numeric;
}

export interface ExchangeItems {
  book_id: number;
  condition: Generated<string>;
  created_at: Generated<Timestamp>;
  exchange_id: Int8;
  id: Generated<Int8>;
  quantity: number;
  total_price: Numeric;
  type: string;
  unit_cost: Numeric | null;
  unit_price: Numeric;
}

export interface ExchangeOutgoingItems {
  book_id: number;
  discount_amount: Generated<Numeric>;
  discount_mode: Generated<string>;
  discount_pct: Generated<Numeric>;
  discount_type: Generated<string>;
  exchange_id: Int8;
  id: Generated<Int8>;
  quantity: number;
  selling_unit_price: Numeric;
  total_price: Numeric;
  unit_cost: Numeric | null;
}

export interface Exchanges {
  branch_id: number;
  created_at: Generated<Timestamp>;
  created_by: number;
  currency: Generated<string>;
  customer_id: number | null;
  customer_id_v2: number | null;
  exchange_reference: string;
  id: Generated<Int8>;
  lifecycle_status: string | null;
  location_id: number | null;
  merchant_id: number | null;
  net_balance: Generated<Numeric>;
  notes: string | null;
  original_order_id: Int8 | null;
  related_payment_id: Int8 | null;
  settlement_type: Generated<string>;
  status: Generated<string>;
  total_incoming_value: Generated<Numeric>;
  total_outgoing_value: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
}

export interface ExchangeSettlementEntries {
  amount: Numeric;
  authorised_by: number | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  entry_type: string;
  exchange_id: Int8;
  id: Generated<Int8>;
  method: string | null;
  note: string | null;
  override_reason: string | null;
}

export interface FinancialTransactions {
  amount: Numeric;
  branch_id: number;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  exchange_id: Int8 | null;
  id: Generated<Int8>;
  idempotency_key: string;
  meta: Generated<Json>;
  method: string | null;
  order_id: Int8 | null;
  receivable_id: Int8 | null;
  staff_id: number;
  type: string;
}

export interface IdempotencyKeys {
  created_at: Generated<Timestamp>;
  endpoint: string;
  expires_at: Generated<Timestamp>;
  key: string;
  request_hash: string;
  response_payload: Json;
}

export interface InstallmentPlans {
  created_at: Generated<Timestamp>;
  created_by: number;
  currency: Generated<string>;
  deposit_amount: Generated<Numeric>;
  id: Generated<Int8>;
  notes: string | null;
  num_installments: number;
  order_id: Int8;
  total_amount: Numeric;
}

export interface Installments {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  due_date: Timestamp;
  id: Generated<Int8>;
  order_id: Int8;
  paid_amount: Generated<Numeric>;
  paid_at: Timestamp | null;
  plan_id: Int8;
  status: Generated<string>;
}

export interface Inventory {
  average_cost: Generated<Numeric>;
  book_id: number;
  damaged_quantity: Generated<number>;
  inventory_value: Generated<Numeric | null>;
  location_id: number;
  quantity: Generated<number>;
  reorder_point: Generated<number>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface InventoryHistory {
  book_id: number;
  created_at: Generated<Timestamp>;
  delta: number;
  id: Generated<Int8>;
  location_id: number;
  movement_type: Generated<string>;
  notes: string | null;
  qty_after: number;
  qty_before: number;
  reason_code: string;
  reference_id: Int8 | null;
  reference_type: string | null;
  staff_id: number;
  total_cost: Numeric | null;
  unit_cost: Numeric | null;
}

export interface InventoryReservations {
  book_id: number;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  location_id: number;
  order_id: Int8;
  quantity: number;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Locations {
  branch_id: number;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_default_fulfillment: Generated<boolean>;
  name: string;
}

export interface LoyaltyAccounts {
  customer_id: number;
  lifetime_points: Generated<Numeric>;
  points_balance: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
}

export interface LoyaltyHistory {
  created_at: Generated<Timestamp>;
  customer_id: number;
  id: Generated<Int8>;
  points_delta: Numeric;
  reason: string;
  transaction_ref: string | null;
}

export interface Merchants {
  address: string | null;
  contact_info: Generated<Json>;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_active: Generated<boolean>;
  name: string;
}

export interface NotificationReads {
  notification_id: Int8;
  read_at: Generated<Timestamp>;
  staff_id: number;
}

export interface Notifications {
  body: string;
  branch_id: number | null;
  created_at: Generated<Timestamp>;
  entity_id: string | null;
  entity_type: string | null;
  event_type: string;
  id: Generated<Int8>;
  is_read: Generated<boolean>;
  read_at: Timestamp | null;
  severity: Generated<string>;
  target_roles: Generated<string[]>;
  target_staff_id: number | null;
  title: string;
}

export interface OrderLineItems {
  book_id: number;
  discount_amount: Generated<Numeric>;
  discount_mode: Generated<string>;
  discount_pct: Generated<Numeric>;
  discount_type: Generated<string>;
  id: Generated<Int8>;
  is_backordered: Generated<boolean>;
  order_id: Int8;
  qty_fulfilled: Generated<number>;
  qty_reserved: Generated<number>;
  quantity: number;
  total_price: Numeric;
  unit_cost: Numeric | null;
  unit_price: Numeric;
}

export interface OrderPayments {
  amount: Numeric;
  bank_account_id: number | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  id: Generated<Int8>;
  notes: string | null;
  order_id: Int8;
  payment_method: string;
  payment_reference: string;
  processed_at: Generated<Timestamp>;
  processed_by: number;
  status: Generated<string>;
  transaction_reference: string | null;
}

export interface OrderRefunds {
  bank_account_id: number | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  order_id: Int8;
  payment_id: Int8;
  processed_by: number;
  reason: string;
  refund_amount: Numeric;
}

export interface Orders {
  branch_id: number;
  cancel_reason: string | null;
  channel: Generated<string>;
  created_at: Generated<Timestamp>;
  created_by: number;
  currency: Generated<string>;
  customer_id: number | null;
  discount_amount: Generated<Numeric>;
  discount_total: Generated<Numeric>;
  id: Generated<Int8>;
  location_id: number | null;
  notes: string | null;
  order_number: string;
  payment_status: Generated<string>;
  sale_type: Generated<string>;
  status: Generated<string>;
  subtotal: Generated<Numeric>;
  tax_amount: Generated<Numeric>;
  tax_rate: Generated<Numeric>;
  total: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
}

export interface Outbox {
  created_at: Generated<Timestamp>;
  event_type: string;
  id: Generated<Int8>;
  payload: Json;
  published_at: Timestamp | null;
  status: Generated<string>;
}

export interface PoLineItems {
  book_id: number;
  edition_id: number | null;
  format_id: number | null;
  id: Generated<Int8>;
  po_id: Int8;
  quantity: number;
  received_quantity: Generated<number>;
  unit_cost: Numeric;
}

export interface PoReceiptItems {
  id: Generated<Int8>;
  po_line_item_id: Int8;
  quantity_received: number;
  receipt_id: Int8;
}

export interface PoReceipts {
  id: Generated<Int8>;
  location_id: number;
  notes: string | null;
  po_id: Int8;
  received_at: Generated<Timestamp>;
  received_by: number;
}

export interface Publishers {
  archived_at: Timestamp | null;
  archived_by: number | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: number | null;
}

export interface PurchaseOrders {
  approved_by: number | null;
  branch_id: number;
  created_at: Generated<Timestamp>;
  created_by: number;
  currency: Generated<string>;
  expected_delivery_date: Timestamp | null;
  financial_status: Generated<string>;
  id: Generated<Int8>;
  notes: string | null;
  payment_terms: Generated<string>;
  receiving_branch_id: number | null;
  receiving_location_id: number | null;
  status: Generated<string>;
  supplier_id: number;
  total_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
}

export interface Receivables {
  branch_id: number;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  customer_id: number;
  due_date: Timestamp | null;
  id: Generated<Int8>;
  notes: string | null;
  original_amount: Numeric;
  outstanding_amount: Generated<Numeric>;
  settlement_date: Timestamp | null;
  source_entity_id: Int8;
  source_ref_id: string;
  source_type: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  write_off_reason: string | null;
  written_off_amount: Numeric | null;
  written_off_at: Timestamp | null;
  written_off_by: number | null;
}

export interface RefreshTokens {
  branch_id: number | null;
  expires_at: Timestamp;
  id: Generated<Int8>;
  revoked: Generated<boolean>;
  role: string | null;
  staff_id: number;
  token_hash: string;
}

export interface Refunds {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  method: string;
  return_id: Int8;
}

export interface ReturnLineItems {
  book_id: number;
  discount_mode: Generated<string>;
  discount_type: Generated<string>;
  id: Generated<Int8>;
  line_refund_amount: Numeric;
  quantity: number;
  return_id: Int8;
  transaction_line_item_id: Int8;
  unit_price: Numeric;
}

export interface Returns {
  approved_by: number | null;
  branch_id: number;
  created_at: Generated<Timestamp>;
  customer_id: number | null;
  id: Generated<Int8>;
  processed_by: number;
  reason: string | null;
  refund_method: string;
  return_number: string;
  status: Generated<string>;
  total_refund_amount: Numeric;
  transaction_id: Int8;
}

export interface Staff {
  created_at: Generated<Timestamp>;
  failed_login_attempts: Generated<number>;
  full_name: string;
  id: Generated<number>;
  is_active: Generated<boolean>;
  is_all_branches: Generated<boolean>;
  last_login_at: Timestamp | null;
  locked_until: Timestamp | null;
  must_change_password: Generated<boolean>;
  password_changed_at: Timestamp | null;
  password_hash: string;
  username: string;
}

export interface StaffBranchRoles {
  branch_id: number;
  id: Generated<number>;
  role: string;
  staff_id: number;
}

export interface StaffLocations {
  location_id: number;
  staff_id: number;
}

export interface StoreCreditAccounts {
  balance: Generated<Numeric>;
  customer_id: number;
}

export interface StoreCreditHistory {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  customer_id: number;
  direction: string;
  id: Generated<Int8>;
  ref_id: string | null;
  ref_type: string | null;
}

export interface SupplierCreditNotes {
  amount: Numeric;
  branch_id: number;
  created_at: Generated<Timestamp>;
  created_by: number;
  id: Generated<number>;
  po_id: Int8;
  reason: string;
  supplier_id: number;
}

export interface SupplierPayments {
  amount: Numeric;
  branch_id: number;
  created_at: Generated<Timestamp>;
  created_by: number;
  id: Generated<Int8>;
  notes: string | null;
  payment_method: Generated<string>;
  po_id: Int8;
  source: Generated<string>;
  supplier_id: number;
}

export interface Suppliers {
  archived_at: Timestamp | null;
  archived_by: number | null;
  contact_info: Json;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  is_active: Generated<boolean>;
  is_blacklisted: Generated<boolean>;
  lead_time_days: Generated<number>;
  name: string;
  pricing_terms: string | null;
  publisher_id: number | null;
  status: Generated<string>;
  supplier_type: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: number | null;
}

export interface SystemConfig {
  key: string;
  updated_at: Generated<Timestamp>;
  updated_by: number;
  value: Json;
}

export interface TransactionLineItems {
  book_id: number;
  discount_amount: Generated<Numeric>;
  discount_mode: Generated<string>;
  discount_pct: Generated<Numeric>;
  discount_type: Generated<string>;
  id: Generated<Int8>;
  line_total: Numeric;
  quantity: number;
  transaction_id: Int8;
  unit_cost: Numeric | null;
  unit_price: Numeric;
}

export interface TransactionPayments {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  method: string;
  reference: string | null;
  transaction_id: Int8;
}

export interface Transactions {
  amount_due: Generated<Numeric>;
  amount_paid: Generated<Numeric>;
  branch_id: number;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  customer_id: number | null;
  discount_total: Generated<Numeric>;
  grand_total: Numeric;
  id: Generated<Int8>;
  location_id: number;
  payment_status: Generated<string>;
  staff_id: number;
  status: Generated<string>;
  subtotal: Numeric;
  tax_total: Generated<Numeric>;
  transaction_number: string;
}

export interface DB {
  audit_logs: AuditLogs;
  authors: Authors;
  bank_accounts: BankAccounts;
  bank_reconciliation: BankReconciliation;
  book_authors: BookAuthors;
  book_branch_prices: BookBranchPrices;
  book_categories: BookCategories;
  book_edit_history: BookEditHistory;
  book_editions: BookEditions;
  book_formats: BookFormats;
  book_suppliers: BookSuppliers;
  book_tags: BookTags;
  books: Books;
  branch_config: BranchConfig;
  branches: Branches;
  categories: Categories;
  customer_group_membership: CustomerGroupMembership;
  customer_groups: CustomerGroups;
  customers: Customers;
  exchange_incoming_items: ExchangeIncomingItems;
  exchange_items: ExchangeItems;
  exchange_outgoing_items: ExchangeOutgoingItems;
  exchange_settlement_entries: ExchangeSettlementEntries;
  exchanges: Exchanges;
  financial_transactions: FinancialTransactions;
  idempotency_keys: IdempotencyKeys;
  installment_plans: InstallmentPlans;
  installments: Installments;
  inventory: Inventory;
  inventory_history: InventoryHistory;
  inventory_reservations: InventoryReservations;
  locations: Locations;
  loyalty_accounts: LoyaltyAccounts;
  loyalty_history: LoyaltyHistory;
  merchants: Merchants;
  notification_reads: NotificationReads;
  notifications: Notifications;
  order_line_items: OrderLineItems;
  order_payments: OrderPayments;
  order_refunds: OrderRefunds;
  orders: Orders;
  outbox: Outbox;
  po_line_items: PoLineItems;
  po_receipt_items: PoReceiptItems;
  po_receipts: PoReceipts;
  publishers: Publishers;
  purchase_orders: PurchaseOrders;
  receivables: Receivables;
  refresh_tokens: RefreshTokens;
  refunds: Refunds;
  return_line_items: ReturnLineItems;
  returns: Returns;
  staff: Staff;
  staff_branch_roles: StaffBranchRoles;
  staff_locations: StaffLocations;
  store_credit_accounts: StoreCreditAccounts;
  store_credit_history: StoreCreditHistory;
  supplier_credit_notes: SupplierCreditNotes;
  supplier_payments: SupplierPayments;
  suppliers: Suppliers;
  system_config: SystemConfig;
  transaction_line_items: TransactionLineItems;
  transaction_payments: TransactionPayments;
  transactions: Transactions;
}
