import type { z } from 'zod';
import {
  AdjustStoreCreditRequestSchema,
  CreateCustomerGroupRequestSchema,
  CreateCustomerRequestSchema,
  CustomerGroupListResponseSchema,
  CustomerGroupSchema,
  CustomerListQuerySchema,
  CustomerListResponseSchema,
  CustomerSchema,
  ListPagingQuerySchema,
  LoyaltyBalanceSchema,
  LoyaltyHistoryResponseSchema,
  RedeemPointsRequestSchema,
  StoreCreditBalanceSchema,
  StoreCreditHistoryResponseSchema,
  UpdateCustomerRequestSchema,
  FinancialTransactionListQuerySchema,
  FinancialTransactionListResponseSchema,
  MarkAllReadResponseSchema,
  MarkReadResponseSchema,
  NotificationIdParamsSchema,
  NotificationListQuerySchema,
  NotificationListResponseSchema,
  UnreadCountResponseSchema,
  AuditLogListQuerySchema,
  AuditLogListResponseSchema,
  BranchListQuerySchema,
  BranchListResponseSchema,
  BranchSchema,
  CreateBranchRequestSchema,
  PublicBranchListResponseSchema,
  UpdateBranchRequestSchema,
  BranchLocationParamsSchema,
  BranchLocationsParamsSchema,
  LocationListResponseSchema,
  LocationNameRequestSchema,
  LocationSchema,
  SetStaffLocationsRequestSchema,
  StaffLocationListResponseSchema,
  BookAvailabilityListResponseSchema,
  BookBranchParamsSchema,
  BookEditListResponseSchema,
  BookListQuerySchema,
  BookListResponseSchema,
  BookPriceListResponseSchema,
  BookSchema,
  BookUsageSchema,
  BranchPriceRequestSchema,
  CatalogSearchQuerySchema,
  CatalogSearchResponseSchema,
  CreateBookRequestSchema,
  QuickRegisterBookRequestSchema,
  SuggestQuerySchema,
  SuggestResponseSchema,
  UpdateBookRequestSchema,
  AuthorListQuerySchema,
  AuthorListResponseSchema,
  AuthorSchema,
  BookLookupListResponseSchema,
  CategoryListQuerySchema,
  CategoryListResponseSchema,
  CategorySchema,
  CreateCategoryRequestSchema,
  PublisherListQuerySchema,
  PublisherListResponseSchema,
  PublisherSchema,
  ReferenceNameRequestSchema,
  ReferenceUsageSchema,
  UpdateCategoryRequestSchema,
  AdjustStockRequestSchema,
  BookStockParamsSchema,
  BookStockQuerySchema,
  BookStockResponseSchema,
  BranchPagingQuerySchema,
  ReorderPointRequestSchema,
  StockInRequestSchema,
  StockLevelListQuerySchema,
  StockLevelListResponseSchema,
  StockLevelSchema,
  StockMovementListQuerySchema,
  StockMovementListResponseSchema,
  StockOutRequestSchema,
  TransferStockRequestSchema,
  TransferStockResponseSchema,
  BranchConfigKeyParamsSchema,
  BranchConfigListResponseSchema,
  BranchConfigParamsSchema,
  ConfigEntrySchema,
  ConfigKeyParamsSchema,
  CurrencyResponseSchema,
  EffectiveConfigQuerySchema,
  EffectiveConfigResponseSchema,
  SetConfigValueRequestSchema,
  SystemConfigListResponseSchema,
  CancelOrderRequestSchema,
  CollectOrderPaymentRequestSchema,
  ConfirmOrderRequestSchema,
  CreateOrderRequestSchema,
  OrderListQuerySchema,
  OrderListResponseSchema,
  OrderSchema,
  BookIdParamsSchema,
  BookSupplierListResponseSchema,
  BookSupplierParamsSchema,
  CreateSupplierRequestSchema,
  HealthResponseSchema,
  IdParamsSchema,
  LinkBookSupplierRequestSchema,
  MessageResponseSchema,
  SupplierListQuerySchema,
  SupplierListResponseSchema,
  SupplierSchema,
  SupplierUsageSchema,
  UpdateSupplierRequestSchema,
  CollectReceivableRequestSchema,
  ReceivableDueDateRequestSchema,
  ReceivableListQuerySchema,
  ReceivableListResponseSchema,
  ReceivableSchema,
  ReceivableSummarySchema,
  WriteOffReceivableRequestSchema,
  CreatePaymentRequestSchema,
  OrderBalanceSchema,
  OrderPaymentListResponseSchema,
  PaymentListQuerySchema,
  PaymentListResponseSchema,
  PaymentRefundListResponseSchema,
  PaymentRefundSchema,
  PaymentSchema,
  RefundPaymentRequestSchema,
  UnpaidListQuerySchema,
  UnpaidListResponseSchema,
} from '@bms/shared';

/**
 * One documented API operation. Each module adds its operations here when it
 * moves to shared contracts (Suppliers in #19, the rest in M5), using the same
 * schemas its routes pass to validate().
 */
export interface ApiOperation {
  /** Unique name for generated clients, e.g. listSuppliers. */
  operationId: string;
  method: 'get' | 'post' | 'put' | 'patch' | 'delete';
  /** Path below /api/v1, with OpenAPI-style parameters: /branches/{id}. */
  path: string;
  summary: string;
  tag: string;
  /** False for public endpoints; everything else needs a bearer token. */
  auth?: boolean;
  request?: {
    params?: z.ZodObject;
    query?: z.ZodObject;
    body?: z.ZodType;
  };
  /** Success responses by status code. */
  responses: Record<number, { description: string; schema?: z.ZodType }>;
  /**
   * Error statuses the operation can return, all with the shared error envelope.
   * Default: 400, 401, 403 and 500 for authenticated operations; 500 for public ones.
   */
  errors?: number[];
}

export const operations: ApiOperation[] = [
  {
    operationId: 'getHealth',
    method: 'get',
    path: '/health',
    summary: 'Service and database health',
    tag: 'System',
    auth: false,
    responses: {
      200: { description: 'The API and its database are available', schema: HealthResponseSchema },
      503: { description: 'The database is unavailable', schema: HealthResponseSchema },
    },
  },
  ...auditOperations(),
  ...branchOperations(),
  ...catalogOperations(),
  ...catalogReferenceOperations(),
  ...configOperations(),
  ...locationOperations(),
  ...customerOperations(),
  ...financialTransactionOperations(),
  ...inventoryOperations(),
  ...notificationOperations(),
  ...supplierOperations(),
  ...orderOperations(),
  ...receivableOperations(),
  ...paymentOperations(),
];

function auditOperations(): ApiOperation[] {
  return [
    {
      operationId: 'listAuditLogs',
      method: 'get',
      path: '/audit-logs',
      summary: 'Audit entries, newest first (Super_Admin, Admin): the session branch\'s; with access to all branches every branch and the entries of no branch, unless ?branchId= asks for one',
      tag: 'Audit',
      request: { query: AuditLogListQuerySchema },
      responses: { 200: { description: 'One page of audit entries', schema: AuditLogListResponseSchema } },
    },
  ];
}

function branchOperations(): ApiOperation[] {
  const tag = 'Branches';
  const headOffice = 'Super_Admin, or Admin with access to all branches';
  const byId = { params: IdParamsSchema };
  return [
    {
      operationId: 'listPublicBranches',
      method: 'get',
      path: '/branches/public',
      summary: 'Active branches for the sign-in page (no token needed)',
      tag,
      auth: false,
      responses: { 200: { description: 'Id and name of each active branch', schema: PublicBranchListResponseSchema } },
    },
    {
      operationId: 'listBranches',
      method: 'get',
      path: '/branches',
      summary: 'List branches by name (?isActive=true|false)',
      tag,
      request: { query: BranchListQuerySchema },
      responses: { 200: { description: 'One page of branches', schema: BranchListResponseSchema } },
    },
    {
      operationId: 'getBranch',
      method: 'get',
      path: '/branches/{id}',
      summary: 'Get a branch',
      tag,
      request: byId,
      responses: { 200: { description: 'The branch', schema: BranchSchema } },
      errors: [400, 401, 403, 404, 500],
    },
    {
      operationId: 'createBranch',
      method: 'post',
      path: '/branches',
      summary: `Open a branch (${headOffice})`,
      tag,
      request: { body: CreateBranchRequestSchema },
      responses: { 201: { description: 'The new branch', schema: BranchSchema } },
      errors: [400, 401, 403, 409, 500],
    },
    {
      operationId: 'updateBranch',
      method: 'put',
      path: '/branches/{id}',
      summary: 'Change some of a branch\'s details (Super_Admin, Admin, Manager; the session branch, or any branch with access to all branches)',
      tag,
      request: { params: IdParamsSchema, body: UpdateBranchRequestSchema },
      responses: { 200: { description: 'The updated branch', schema: BranchSchema } },
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      operationId: 'deactivateBranch',
      method: 'post',
      path: '/branches/{id}/deactivate',
      summary: `Close a branch (${headOffice})`,
      tag,
      request: byId,
      responses: { 200: { description: 'Deactivated', schema: MessageResponseSchema } },
      errors: [400, 401, 403, 404, 500],
    },
    {
      operationId: 'reactivateBranch',
      method: 'post',
      path: '/branches/{id}/reactivate',
      summary: `Reopen a branch (${headOffice})`,
      tag,
      request: byId,
      responses: { 200: { description: 'Reactivated', schema: MessageResponseSchema } },
      errors: [400, 401, 403, 404, 500],
    },
    {
      operationId: 'deleteBranch',
      method: 'delete',
      path: '/branches/{id}',
      summary: `Delete a branch that nothing belongs to any more (${headOffice})`,
      tag,
      request: byId,
      responses: { 200: { description: 'Deleted', schema: MessageResponseSchema } },
      errors: [400, 401, 403, 404, 409, 500],
    },
  ];
}

function configOperations(): ApiOperation[] {
  const tag = 'Configuration';
  return [
    {
      operationId: 'listSystemConfig',
      method: 'get',
      path: '/config/system',
      summary: 'List the system settings (Super_Admin, Admin, Manager)',
      tag,
      responses: { 200: { description: 'Every system setting, by key', schema: SystemConfigListResponseSchema } },
      errors: [401, 403, 500],
    },
    {
      operationId: 'setSystemConfig',
      method: 'put',
      path: '/config/system/{key}',
      summary: 'Set a system setting (Super_Admin); the value must have the key\'s type',
      tag,
      request: { params: ConfigKeyParamsSchema, body: SetConfigValueRequestSchema },
      responses: { 200: { description: 'The saved setting', schema: ConfigEntrySchema } },
    },
    {
      operationId: 'getCurrency',
      method: 'get',
      path: '/config/currency',
      summary: 'The session branch\'s currency (ETB when it cannot be read)',
      tag,
      responses: { 200: { description: 'The currency code', schema: CurrencyResponseSchema } },
      errors: [401, 403, 500],
    },
    {
      operationId: 'getEffectiveConfig',
      method: 'get',
      path: '/config/effective',
      summary: 'The session branch\'s effective values for ?keys=a,b (null for a key set nowhere)',
      tag,
      request: { query: EffectiveConfigQuerySchema },
      responses: { 200: { description: 'One entry per requested key', schema: EffectiveConfigResponseSchema } },
    },
    {
      operationId: 'listBranchConfig',
      method: 'get',
      path: '/config/branches/{branchId}',
      summary: 'A branch\'s effective settings, each marked branch or system (Super_Admin, Admin, Manager; the session branch, or any branch with access to all branches)',
      tag,
      request: { params: BranchConfigParamsSchema },
      responses: { 200: { description: 'Every system key with its effective value', schema: BranchConfigListResponseSchema } },
    },
    {
      operationId: 'setBranchConfig',
      method: 'put',
      path: '/config/branches/{branchId}/{key}',
      summary: 'Override a setting for a branch (Super_Admin, Admin, Manager; the session branch, or any branch with access to all branches)',
      tag,
      request: { params: BranchConfigKeyParamsSchema, body: SetConfigValueRequestSchema },
      responses: { 200: { description: 'The saved override', schema: ConfigEntrySchema } },
      errors: [400, 401, 403, 404, 500],
    },
    {
      operationId: 'removeBranchConfig',
      method: 'delete',
      path: '/config/branches/{branchId}/{key}',
      summary: 'Remove a branch override, so the system default applies again (Super_Admin, Admin; the session branch, or any branch with access to all branches)',
      tag,
      request: { params: BranchConfigKeyParamsSchema },
      responses: { 200: { description: 'Removed', schema: MessageResponseSchema } },
      errors: [400, 401, 403, 404, 500],
    },
  ];
}

function locationOperations(): ApiOperation[] {
  const tag = 'Locations';
  const inScope = 'the session branch, or any branch with access to all branches';
  return [
    {
      operationId: 'listLocations',
      method: 'get',
      path: '/branches/{branchId}/locations',
      summary: 'List a branch\'s locations, default first (staff with location restrictions get only theirs)',
      tag,
      request: { params: BranchLocationsParamsSchema },
      responses: { 200: { description: 'The locations and the caller\'s access mode', schema: LocationListResponseSchema } },
    },
    {
      operationId: 'createLocation',
      method: 'post',
      path: '/branches/{branchId}/locations',
      summary: `Add a location to a branch (Super_Admin, Admin, Manager; ${inScope})`,
      tag,
      request: { params: BranchLocationsParamsSchema, body: LocationNameRequestSchema },
      responses: { 201: { description: 'The new location', schema: LocationSchema } },
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      operationId: 'renameLocation',
      method: 'put',
      path: '/branches/{branchId}/locations/{id}',
      summary: `Rename a location (Super_Admin, Admin, Manager; ${inScope})`,
      tag,
      request: { params: BranchLocationParamsSchema, body: LocationNameRequestSchema },
      responses: { 200: { description: 'The renamed location', schema: LocationSchema } },
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      operationId: 'setDefaultLocation',
      method: 'put',
      path: '/branches/{branchId}/locations/{id}/set-default',
      summary: `Make a location the branch's default for fulfilment (Super_Admin, Admin, Manager; ${inScope})`,
      tag,
      request: { params: BranchLocationParamsSchema },
      responses: { 200: { description: 'The new default location', schema: LocationSchema } },
      errors: [400, 401, 403, 404, 500],
    },
    {
      operationId: 'deleteLocation',
      method: 'delete',
      path: '/branches/{branchId}/locations/{id}',
      summary: `Delete a location without stock or history (Super_Admin, Admin, Manager; ${inScope})`,
      tag,
      request: { params: BranchLocationParamsSchema },
      responses: { 200: { description: 'Deleted', schema: MessageResponseSchema } },
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      operationId: 'listStaffLocations',
      method: 'get',
      path: '/staff/{id}/locations',
      summary: 'A staff member\'s location restrictions in every branch (Super_Admin, Admin, Manager)',
      tag,
      request: { params: IdParamsSchema },
      responses: { 200: { description: 'The assigned locations', schema: StaffLocationListResponseSchema } },
    },
    {
      operationId: 'setStaffLocations',
      method: 'put',
      path: '/staff/{id}/locations',
      summary: 'Replace a staff member\'s location restrictions; [] lifts them. Other branches\' locations must be sent back unchanged unless the caller has access to all branches',
      tag,
      request: { params: IdParamsSchema, body: SetStaffLocationsRequestSchema },
      responses: { 200: { description: 'Saved', schema: MessageResponseSchema } },
    },
  ];
}

function customerOperations(): ApiOperation[] {
  const tag = 'Customers';
  const byId = { params: IdParamsSchema };
  const history = { params: IdParamsSchema, query: ListPagingQuerySchema };
  const notFound = [400, 401, 403, 404, 500];
  const correction = 'a back-office correction with a reason (Admin, Manager, Finance_Officer); at checkout customers spend it as a payment';
  return [
    {
      operationId: 'listCustomers',
      method: 'get',
      path: '/customers',
      summary: 'Search customers by name, phone, email or code (shared by every branch; ?status=active by default when given)',
      tag,
      request: { query: CustomerListQuerySchema },
      responses: { 200: { description: 'One page of customers, by name', schema: CustomerListResponseSchema } },
    },
    {
      operationId: 'createCustomer',
      method: 'post',
      path: '/customers',
      summary: 'Create a customer with empty loyalty and store-credit accounts (Admin, Manager, Sales)',
      tag,
      request: { body: CreateCustomerRequestSchema },
      responses: { 201: { description: 'The new customer', schema: CustomerSchema } },
      errors: [400, 401, 403, 409, 500],
    },
    {
      operationId: 'getCustomer',
      method: 'get',
      path: '/customers/{id}',
      summary: 'Get a customer with balances and groups',
      tag,
      request: byId,
      responses: { 200: { description: 'The customer', schema: CustomerSchema } },
      errors: notFound,
    },
    {
      operationId: 'updateCustomer',
      method: 'put',
      path: '/customers/{id}',
      summary: 'Change some of a customer\'s details (Admin, Manager, Sales)',
      tag,
      request: { params: IdParamsSchema, body: UpdateCustomerRequestSchema },
      responses: { 200: { description: 'The updated customer', schema: CustomerSchema } },
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      operationId: 'deactivateCustomer',
      method: 'post',
      path: '/customers/{id}/deactivate',
      summary: 'Set a customer to INACTIVE (Admin, Manager)',
      tag,
      request: byId,
      responses: { 200: { description: 'Deactivated', schema: MessageResponseSchema } },
      errors: notFound,
    },
    {
      operationId: 'listCustomerGroups',
      method: 'get',
      path: '/customer-groups',
      summary: 'List customer groups by name',
      tag,
      responses: { 200: { description: 'Every group', schema: CustomerGroupListResponseSchema } },
      errors: [401, 403, 500],
    },
    {
      operationId: 'createCustomerGroup',
      method: 'post',
      path: '/customer-groups',
      summary: 'Create a customer group (Admin, Manager)',
      tag,
      request: { body: CreateCustomerGroupRequestSchema },
      responses: { 201: { description: 'The new group', schema: CustomerGroupSchema } },
    },
    {
      operationId: 'getCustomerLoyalty',
      method: 'get',
      path: '/customers/{id}/loyalty',
      summary: 'A customer\'s loyalty points',
      tag,
      request: byId,
      responses: { 200: { description: 'Points balance and lifetime points', schema: LoyaltyBalanceSchema } },
      errors: notFound,
    },
    {
      operationId: 'listCustomerLoyaltyHistory',
      method: 'get',
      path: '/customers/{id}/loyalty/history',
      summary: 'A customer\'s loyalty point movements, newest first',
      tag,
      request: history,
      responses: { 200: { description: 'One page of movements', schema: LoyaltyHistoryResponseSchema } },
    },
    {
      operationId: 'redeemCustomerPoints',
      method: 'post',
      path: '/customers/{id}/loyalty/redeem',
      summary: `Take points off a customer: ${correction}`,
      tag,
      request: { params: IdParamsSchema, body: RedeemPointsRequestSchema },
      responses: { 200: { description: 'Redeemed', schema: MessageResponseSchema } },
      errors: [400, 401, 403, 404, 422, 500],
    },
    {
      operationId: 'getCustomerStoreCredit',
      method: 'get',
      path: '/customers/{id}/store-credit',
      summary: 'A customer\'s store-credit balance',
      tag,
      request: byId,
      responses: { 200: { description: 'The balance', schema: StoreCreditBalanceSchema } },
      errors: notFound,
    },
    {
      operationId: 'listCustomerStoreCreditHistory',
      method: 'get',
      path: '/customers/{id}/store-credit/history',
      summary: 'A customer\'s store-credit movements, newest first',
      tag,
      request: history,
      responses: { 200: { description: 'One page of movements', schema: StoreCreditHistoryResponseSchema } },
    },
    {
      operationId: 'adjustCustomerStoreCredit',
      method: 'post',
      path: '/customers/{id}/store-credit/adjust',
      summary: `Add or take off store credit: ${correction}`,
      tag,
      request: { params: IdParamsSchema, body: AdjustStoreCreditRequestSchema },
      responses: { 200: { description: 'Applied', schema: MessageResponseSchema } },
      errors: [400, 401, 403, 404, 422, 500],
    },
  ];
}

function catalogOperations(): ApiOperation[] {
  const tag = 'Books';
  const byId = { params: IdParamsSchema };
  const edit = 'Admin, Manager, Stock_Clerk';
  const lifecycle = [
    ['deactivate', 'deactivateBook', 'Set an active book inactive; it can no longer be sold or ordered'],
    ['reactivate', 'reactivateBook', 'Set an inactive book active; an archived one must be restored'],
    ['archive', 'archiveBook', 'Archive a book (from active or inactive); hidden by default'],
    ['restore', 'restoreBook', 'Restore an archived book to active'],
  ] as const;
  return [
    {
      operationId: 'listBooks',
      method: 'get',
      path: '/books',
      summary: 'Books by title (active only unless ?is_active= or ?status= says otherwise), with the price in ?branchId= or the session branch',
      tag,
      request: { query: BookListQuerySchema },
      responses: { 200: { description: 'One page of books', schema: BookListResponseSchema } },
    },
    {
      operationId: 'listBooksWithAvailability',
      method: 'get',
      path: '/books/with-availability',
      summary: 'Like GET /books, with the stock at ?locationId= (for the sale and receiving screens)',
      tag,
      request: { query: BookListQuerySchema },
      responses: { 200: { description: 'One page of books with their stock', schema: BookAvailabilityListResponseSchema } },
    },
    {
      operationId: 'searchCatalog',
      method: 'get',
      path: '/catalog/search',
      summary: 'Active books matching a term (title, author, ISBN-10 or -13, SKU, publisher, description), without paging',
      tag,
      request: { query: CatalogSearchQuerySchema },
      responses: { 200: { description: 'Matching books, by title', schema: CatalogSearchResponseSchema } },
    },
    {
      operationId: 'suggestAuthors',
      method: 'get',
      path: '/catalog/authors/suggest',
      summary: 'Active author names starting with ?q=',
      tag,
      request: { query: SuggestQuerySchema },
      responses: { 200: { description: 'Up to 10 names', schema: SuggestResponseSchema } },
    },
    {
      operationId: 'suggestCategories',
      method: 'get',
      path: '/catalog/categories/suggest',
      summary: 'Active category names starting with ?q=',
      tag,
      request: { query: SuggestQuerySchema },
      responses: { 200: { description: 'Up to 10 names', schema: SuggestResponseSchema } },
    },
    {
      operationId: 'getBook',
      method: 'get',
      path: '/books/{id}',
      summary: 'One book, with the price in ?branchId= or the session branch',
      tag,
      request: { params: IdParamsSchema, query: BookListQuerySchema.pick({ branchId: true }) },
      responses: { 200: { description: 'The book', schema: BookSchema } },
      errors: [400, 401, 404, 500],
    },
    {
      operationId: 'listBookPrices',
      method: 'get',
      path: '/books/{id}/prices',
      summary: 'The prices branches have set for a book',
      tag,
      request: byId,
      responses: { 200: { description: 'One price per branch that has its own', schema: BookPriceListResponseSchema } },
      errors: [400, 401, 404, 500],
    },
    {
      operationId: 'listBookEdits',
      method: 'get',
      path: '/books/{id}/history',
      summary: 'Changes to a book\'s details, newest first (Admin, Manager)',
      tag,
      request: { params: IdParamsSchema, query: ListPagingQuerySchema },
      responses: { 200: { description: 'One page of changes', schema: BookEditListResponseSchema } },
      errors: [400, 401, 403, 500],
    },
    {
      operationId: 'getBookUsage',
      method: 'get',
      path: '/catalog/{id}/usage',
      summary: `What refers to a book: stock, sales, orders, returns, exchanges, purchase orders (${edit})`,
      tag,
      request: byId,
      responses: { 200: { description: 'Usage by kind', schema: BookUsageSchema } },
      errors: [400, 401, 403, 404, 500],
    },
    {
      operationId: 'createBook',
      method: 'post',
      path: '/books',
      summary: `Add a book; an ISBN-10 is stored as its ISBN-13, and authors and categories given by name are matched ignoring letter case (${edit})`,
      tag,
      request: { body: CreateBookRequestSchema },
      responses: { 201: { description: 'The new book', schema: BookSchema } },
      errors: [400, 401, 403, 404, 409, 422, 500],
    },
    {
      operationId: 'quickRegisterBook',
      method: 'post',
      path: '/books/quick-register',
      summary: 'Add a catalog-only book from the sale screens (CREATE_SALE); no stock',
      tag,
      request: { body: QuickRegisterBookRequestSchema },
      responses: { 201: { description: 'The new book', schema: BookSchema } },
      errors: [400, 401, 403, 409, 422, 500],
    },
    {
      operationId: 'updateBook',
      method: 'put',
      path: '/books/{id}',
      summary: `Change a book; changed details are kept in its history (${edit})`,
      tag,
      request: { params: IdParamsSchema, body: UpdateBookRequestSchema },
      responses: { 200: { description: 'The book after the change', schema: BookSchema } },
      errors: [400, 401, 403, 404, 422, 500],
    },
    {
      operationId: 'deleteBook',
      method: 'delete',
      path: '/books/{id}',
      summary: 'Delete a book nothing refers to; archive the others (Admin)',
      tag,
      request: byId,
      responses: { 200: { description: 'Deleted', schema: MessageResponseSchema } },
      errors: [400, 401, 403, 404, 409, 500],
    },
    ...lifecycle.map(([action, operationId, summary]): ApiOperation => ({
      operationId,
      method: 'post',
      path: `/books/{id}/${action}`,
      summary: `${summary}; repeating the current status changes nothing (${edit})`,
      tag,
      request: byId,
      responses: { 200: { description: 'Done', schema: MessageResponseSchema } },
      errors: [400, 401, 403, 404, 422, 500],
    })),
    {
      operationId: 'setBookBranchPrice',
      method: 'put',
      path: '/books/{id}/prices/{branchId}',
      summary: 'Set a book\'s price in the session branch, or in any branch with access to all branches (Admin, Manager)',
      tag,
      request: { params: BookBranchParamsSchema, body: BranchPriceRequestSchema },
      responses: { 200: { description: 'Updated', schema: MessageResponseSchema } },
      errors: [400, 401, 403, 404, 500],
    },
  ];
}

function catalogReferenceOperations(): ApiOperation[] {
  const tag = 'Catalog reference data';
  const byId = { params: IdParamsSchema };
  const edit = 'Admin, Manager, Stock_Clerk';
  const kinds = [
    {
      kind: 'author',
      path: '/authors',
      label: 'Author',
      plural: 'authors',
      schema: AuthorSchema,
      list: { query: AuthorListQuerySchema, response: AuthorListResponseSchema },
      create: ReferenceNameRequestSchema,
      update: ReferenceNameRequestSchema,
    },
    {
      kind: 'category',
      path: '/categories',
      label: 'Category',
      plural: 'categories',
      schema: CategorySchema,
      list: { query: CategoryListQuerySchema, response: CategoryListResponseSchema },
      create: CreateCategoryRequestSchema,
      update: UpdateCategoryRequestSchema,
    },
    {
      kind: 'publisher',
      path: '/publishers',
      label: 'Publisher',
      plural: 'publishers',
      schema: PublisherSchema,
      list: { query: PublisherListQuerySchema, response: PublisherListResponseSchema },
      create: ReferenceNameRequestSchema,
      update: ReferenceNameRequestSchema,
    },
  ] as const;
  const id = (k: string) => k.charAt(0).toUpperCase() + k.slice(1);
  const lifecycle = [
    ['archive', 'Archive', 'Archive (from active or inactive); hidden from pickers'],
    ['restore', 'Restore', 'Restore an archived record to active'],
    ['deactivate', 'Deactivate', 'Set an active record inactive'],
    ['activate', 'Activate', 'Set an inactive record active; an archived one must be restored'],
  ] as const;
  return [
    ...kinds.flatMap((k): ApiOperation[] => [
      {
        operationId: `list${id(k.plural)}`,
        method: 'get',
        path: k.path,
        summary: `List ${k.plural} by name, with how many books use each (active only unless ?status= says otherwise)`,
        tag,
        request: { query: k.list.query },
        responses: { 200: { description: `One page of ${k.plural}`, schema: k.list.response } },
      },
      {
        operationId: `create${id(k.kind)}`,
        method: 'post',
        path: k.path,
        summary: `Create ${k.kind === 'author' ? 'an' : 'a'} ${k.kind}; names are unique ignoring letter case (${edit})`,
        tag,
        request: { body: k.create },
        responses: { 201: { description: `The new ${k.kind}`, schema: k.schema } },
        errors: [400, 401, 403, 404, 409, 500],
      },
      {
        operationId: `update${id(k.kind)}`,
        method: 'put',
        path: `${k.path}/{id}`,
        summary: `Change ${k.kind === 'author' ? 'an' : 'a'} ${k.kind} (${edit})`,
        tag,
        request: { params: IdParamsSchema, body: k.update },
        responses: { 200: { description: `The ${k.kind} after the change`, schema: k.schema } },
        errors: [400, 401, 403, 404, 409, 500],
      },
      {
        operationId: `delete${id(k.kind)}`,
        method: 'delete',
        path: `${k.path}/{id}`,
        summary: `Delete ${k.kind === 'author' ? 'an' : 'a'} ${k.kind} no book uses; archive one in use (Admin)`,
        tag,
        request: byId,
        responses: { 200: { description: 'Deleted', schema: MessageResponseSchema } },
        errors: [400, 401, 403, 404, 409, 500],
      },
      {
        operationId: `get${id(k.kind)}Usage`,
        method: 'get',
        path: `${k.path}/{id}/usage`,
        summary: `How many books use the ${k.kind} (${edit})`,
        tag,
        request: byId,
        responses: { 200: { description: 'Usage by kind', schema: ReferenceUsageSchema } },
        errors: [400, 401, 403, 404, 500],
      },
      ...lifecycle.map(([action, verb, summary]): ApiOperation => ({
        operationId: `${action}${id(k.kind)}`,
        method: 'post',
        path: `${k.path}/{id}/${action}`,
        summary: `${summary}; repeating the current status changes nothing (${edit})`,
        tag,
        request: byId,
        responses: { 200: { description: `${verb}d`, schema: MessageResponseSchema } },
        errors: [400, 401, 403, 404, 422, 500],
      })),
    ]),
    {
      operationId: 'listBookFormats',
      method: 'get',
      path: '/book-formats',
      summary: 'The book formats, in display order',
      tag,
      responses: { 200: { description: 'All formats', schema: BookLookupListResponseSchema } },
    },
    {
      operationId: 'listBookEditions',
      method: 'get',
      path: '/book-editions',
      summary: 'The book editions, in display order',
      tag,
      responses: { 200: { description: 'All editions', schema: BookLookupListResponseSchema } },
    },
  ];
}

function financialTransactionOperations(): ApiOperation[] {
  const tag = 'Financial transactions';
  return [
    {
      operationId: 'listFinancialTransactions',
      method: 'get',
      path: '/financial-transactions',
      summary: 'The session branch\'s ledger entries, newest first (?branchId= another branch needs access to all branches)',
      tag,
      request: { query: FinancialTransactionListQuerySchema },
      responses: { 200: { description: 'One page of ledger entries', schema: FinancialTransactionListResponseSchema } },
    },
    {
      operationId: 'createFinancialTransaction',
      method: 'post',
      path: '/financial-transactions',
      summary: 'Retired: entries are written by POST /payments, collection and exchange settlement',
      tag,
      responses: {},
      errors: [401, 403, 410],
    },
  ];
}

function inventoryOperations(): ApiOperation[] {
  const tag = 'Inventory';
  const otherBranch = '?branchId= another branch needs access to all branches';
  const move = 'Admin, Manager, Stock_Clerk; at a location of the session branch the caller may use';
  const change = [400, 401, 403, 404, 409, 422, 500];
  return [
    {
      operationId: 'listStockLevels',
      method: 'get',
      path: '/inventory',
      summary: `Stock per book and location in the session branch, active books by default (${otherBranch})`,
      tag,
      request: { query: StockLevelListQuerySchema },
      responses: { 200: { description: 'One page of stock levels', schema: StockLevelListResponseSchema } },
    },
    {
      operationId: 'listLowStock',
      method: 'get',
      path: '/inventory/low-stock',
      summary: `Active books at or below their reorder point, emptiest first (${otherBranch})`,
      tag,
      request: { query: BranchPagingQuerySchema },
      responses: { 200: { description: 'One page of stock levels', schema: StockLevelListResponseSchema } },
    },
    {
      operationId: 'listStockMovements',
      method: 'get',
      path: '/inventory/history',
      summary: `Stock movements in the session branch, newest first (${otherBranch})`,
      tag,
      request: { query: StockMovementListQuerySchema },
      responses: { 200: { description: 'One page of stock movements', schema: StockMovementListResponseSchema } },
    },
    {
      operationId: 'getBookStock',
      method: 'get',
      path: '/inventory/book/{bookId}/breakdown',
      summary: 'Where a book is in stock, per location (any branch; the session branch when none is given)',
      tag,
      request: { params: BookStockParamsSchema, query: BookStockQuerySchema },
      responses: { 200: { description: 'Stock per location', schema: BookStockResponseSchema } },
    },
    {
      operationId: 'adjustStock',
      method: 'post',
      path: '/inventory/adjust',
      summary: `Correct stock by hand: damage and loss reduce it, a return adds to it, a correction goes either way (${move})`,
      tag,
      request: { body: AdjustStockRequestSchema },
      responses: { 200: { description: 'The stock level after the change', schema: StockLevelSchema } },
      errors: change,
    },
    {
      operationId: 'transferStock',
      method: 'post',
      path: '/inventory/transfer',
      summary: `Move stock between two locations of the session branch (${move}, for the source)`,
      tag,
      request: { body: TransferStockRequestSchema },
      responses: { 200: { description: 'Both stock levels after the move', schema: TransferStockResponseSchema } },
      errors: change,
    },
    {
      operationId: 'stockIn',
      method: 'post',
      path: '/inventory/stock-in',
      summary: `Receive stock by hand (${move})`,
      tag,
      request: { body: StockInRequestSchema },
      responses: { 200: { description: 'The stock level after the change', schema: StockLevelSchema } },
      errors: change,
    },
    {
      operationId: 'stockOut',
      method: 'post',
      path: '/inventory/stock-out',
      summary: `Issue stock by hand; sales go through POS and orders (${move})`,
      tag,
      request: { body: StockOutRequestSchema },
      responses: { 200: { description: 'The stock level after the change', schema: StockLevelSchema } },
      errors: change,
    },
    {
      operationId: 'setReorderPoint',
      method: 'put',
      path: '/inventory/reorder-point',
      summary: 'Set the quantity at which a book counts as low stock at a location of the session branch (Admin, Manager)',
      tag,
      request: { body: ReorderPointRequestSchema },
      responses: { 200: { description: 'The stock level after the change', schema: StockLevelSchema } },
      errors: [400, 401, 403, 404, 500],
    },
    {
      operationId: 'initializeStock',
      method: 'post',
      path: '/inventory/initialize',
      summary: 'Retired: stock in and transfers create the stock record when needed',
      tag,
      responses: {},
      errors: [401, 403, 410],
    },
  ];
}

function notificationOperations(): ApiOperation[] {
  const tag = 'Notifications';
  const scope = 'addressed to the caller, or to their role in the session branch or system-wide; staff with access to all branches see every branch';
  return [
    {
      operationId: 'listNotifications',
      method: 'get',
      path: '/notifications',
      summary: `The caller's notifications, newest first (${scope})`,
      tag,
      request: { query: NotificationListQuerySchema },
      responses: { 200: { description: 'One page of notifications', schema: NotificationListResponseSchema } },
    },
    {
      operationId: 'countUnreadNotifications',
      method: 'get',
      path: '/notifications/unread-count',
      summary: 'How many of the caller\'s notifications are unread',
      tag,
      responses: { 200: { description: 'The unread count', schema: UnreadCountResponseSchema } },
      errors: [401, 403, 500],
    },
    {
      operationId: 'markNotificationRead',
      method: 'put',
      path: '/notifications/{id}/read',
      summary: 'Mark one of the caller\'s notifications as read (a notification they cannot see is left alone)',
      tag,
      request: { params: NotificationIdParamsSchema },
      responses: { 200: { description: 'Done', schema: MarkReadResponseSchema } },
    },
    {
      operationId: 'markAllNotificationsRead',
      method: 'put',
      path: '/notifications/read-all',
      summary: 'Mark all of the caller\'s unread notifications as read',
      tag,
      responses: { 200: { description: 'How many were marked', schema: MarkAllReadResponseSchema } },
      errors: [401, 403, 500],
    },
  ];
}

function supplierOperations(): ApiOperation[] {
  const tag = 'Suppliers';
  const byId = { params: IdParamsSchema };
  const action = (operationId: string, verb: string, summary: string, errors: number[]): ApiOperation => ({
    operationId,
    method: 'post',
    path: `/suppliers/{id}/${verb}`,
    summary,
    tag,
    request: byId,
    responses: { 200: { description: 'Done', schema: MessageResponseSchema } },
    errors,
  });
  return [
    {
      operationId: 'listSuppliers',
      method: 'get',
      path: '/suppliers',
      summary: 'List suppliers (active only when ?status=active; ?status=all for every status)',
      tag,
      request: { query: SupplierListQuerySchema },
      responses: { 200: { description: 'One page of suppliers, by name', schema: SupplierListResponseSchema } },
    },
    {
      operationId: 'createSupplier',
      method: 'post',
      path: '/suppliers',
      summary: 'Create a supplier',
      tag,
      request: { body: CreateSupplierRequestSchema },
      responses: { 201: { description: 'The new supplier', schema: SupplierSchema } },
      errors: [400, 401, 403, 409, 422, 500],
    },
    {
      operationId: 'getSupplier',
      method: 'get',
      path: '/suppliers/{id}',
      summary: 'Get a supplier',
      tag,
      request: byId,
      responses: { 200: { description: 'The supplier', schema: SupplierSchema } },
      errors: [400, 401, 403, 404, 500],
    },
    {
      operationId: 'updateSupplier',
      method: 'put',
      path: '/suppliers/{id}',
      summary: 'Change some of a supplier\'s fields',
      tag,
      request: { params: IdParamsSchema, body: UpdateSupplierRequestSchema },
      responses: { 200: { description: 'The updated supplier', schema: SupplierSchema } },
      errors: [400, 401, 403, 404, 409, 422, 500],
    },
    {
      operationId: 'deleteSupplier',
      method: 'delete',
      path: '/suppliers/{id}',
      summary: 'Delete a supplier that has no purchase orders (Admin, Manager)',
      tag,
      request: byId,
      responses: { 200: { description: 'Deleted', schema: MessageResponseSchema } },
      errors: [400, 401, 403, 404, 409, 500],
    },
    action('deactivateSupplier', 'deactivate', 'Set a supplier to INACTIVE', [400, 401, 403, 404, 500]),
    action('activateSupplier', 'activate', 'Set a supplier to ACTIVE', [400, 401, 403, 404, 500]),
    action('archiveSupplier', 'archive', 'Archive a supplier', [400, 401, 403, 404, 500]),
    action('restoreSupplier', 'restore', 'Restore an archived supplier to ACTIVE', [400, 401, 403, 404, 500]),
    action('blacklistSupplier', 'blacklist', 'Blacklist a supplier (Admin, Manager)', [400, 401, 403, 404, 500]),
    {
      operationId: 'getSupplierUsage',
      method: 'get',
      path: '/suppliers/{id}/usage',
      summary: 'Count the records that keep a supplier from being deleted',
      tag,
      request: byId,
      responses: { 200: { description: 'Counts by record type', schema: SupplierUsageSchema } },
      errors: [400, 401, 403, 404, 500],
    },
    {
      operationId: 'listBookSuppliers',
      method: 'get',
      path: '/books/{bookId}/suppliers',
      summary: 'List a book\'s suppliers, primary first',
      tag,
      request: { params: BookIdParamsSchema },
      responses: { 200: { description: 'The book\'s suppliers', schema: BookSupplierListResponseSchema } },
      errors: [400, 401, 500],
    },
    {
      operationId: 'linkBookSupplier',
      method: 'post',
      path: '/books/{bookId}/suppliers',
      summary: 'Link a supplier to a book, or update the link (Admin, Manager)',
      tag,
      request: { params: BookIdParamsSchema, body: LinkBookSupplierRequestSchema },
      responses: { 201: { description: 'Linked', schema: MessageResponseSchema } },
    },
    {
      operationId: 'unlinkBookSupplier',
      method: 'delete',
      path: '/books/{bookId}/suppliers/{supplierId}',
      summary: 'Remove a supplier from a book (Admin, Manager)',
      tag,
      request: { params: BookSupplierParamsSchema },
      responses: { 200: { description: 'Unlinked', schema: MessageResponseSchema } },
    },
  ];
}

function orderOperations(): ApiOperation[] {
  const tag = 'Orders';
  const byId = { params: IdParamsSchema };
  const order = (description: string) => ({ 200: { description, schema: OrderSchema } });
  return [
    {
      operationId: 'listOrders',
      method: 'get',
      path: '/orders',
      summary: 'List the session branch\'s orders, newest first (?branchId= another branch needs access to all branches)',
      tag,
      request: { query: OrderListQuerySchema },
      responses: { 200: { description: 'One page of orders', schema: OrderListResponseSchema } },
    },
    {
      operationId: 'createOrder',
      method: 'post',
      path: '/orders',
      summary: 'Create a draft order (send an Idempotency-Key header to make retries safe)',
      tag,
      request: { body: CreateOrderRequestSchema },
      responses: {
        201: { description: 'The new draft order', schema: OrderSchema },
        200: { description: 'Replay of an earlier request with the same Idempotency-Key', schema: OrderSchema },
      },
      errors: [400, 401, 403, 404, 409, 422, 500],
    },
    {
      operationId: 'getOrder',
      method: 'get',
      path: '/orders/{id}',
      summary: 'Get an order with its lines',
      tag,
      request: byId,
      responses: order('The order'),
      errors: [400, 401, 403, 404, 500],
    },
    {
      operationId: 'deleteOrder',
      method: 'delete',
      path: '/orders/{id}',
      summary: 'Delete a draft or cancelled order without payment or stock history (Admin)',
      tag,
      request: byId,
      responses: { 200: { description: 'Deleted', schema: MessageResponseSchema } },
      errors: [400, 401, 403, 404, 422, 500],
    },
    {
      operationId: 'confirmOrder',
      method: 'post',
      path: '/orders/{id}/confirm',
      summary: 'Confirm a draft: takes the stock out, then records the cash payment or opens the receivable',
      tag,
      request: { params: IdParamsSchema, body: ConfirmOrderRequestSchema },
      responses: order('The confirmed order'),
      errors: [400, 401, 403, 404, 422, 500],
    },
    {
      operationId: 'fulfillOrder',
      method: 'post',
      path: '/orders/{id}/fulfill',
      summary: 'Hand over a confirmed order (it becomes COMPLETED)',
      tag,
      request: byId,
      responses: order('The completed order'),
      errors: [400, 401, 403, 404, 422, 500],
    },
    {
      operationId: 'cancelOrder',
      method: 'post',
      path: '/orders/{id}/cancel',
      summary: 'Cancel an unfulfilled order: restores stock and settles its receivable',
      tag,
      request: { params: IdParamsSchema, body: CancelOrderRequestSchema },
      responses: order('The cancelled order'),
      errors: [400, 401, 403, 404, 422, 500],
    },
    {
      operationId: 'collectOrderPayment',
      method: 'post',
      path: '/orders/{id}/collect-payment',
      summary: 'Collect a payment against a fulfilled credit order\'s receivable',
      tag,
      request: { params: IdParamsSchema, body: CollectOrderPaymentRequestSchema },
      responses: order('The order with its new payment status'),
      errors: [400, 401, 403, 404, 422, 500],
    },
    {
      operationId: 'progressOrder',
      method: 'post',
      path: '/orders/{id}/progress',
      summary: 'Legacy: move a pre-v1.1 Confirmed order to In_Progress (#69)',
      tag,
      request: byId,
      responses: order('The order'),
      errors: [400, 401, 403, 404, 422, 500],
    },
    {
      operationId: 'payOrder',
      method: 'post',
      path: '/orders/{id}/pay',
      summary: 'Retired: record payments with POST /payments',
      tag,
      request: byId,
      responses: {},
      errors: [401, 403, 404, 410],
    },
  ];
}

function receivableOperations(): ApiOperation[] {
  const tag = 'Receivables';
  const receivable = (description: string) => ({ 200: { description, schema: ReceivableSchema } });
  const change = [400, 401, 403, 404, 422, 500];
  return [
    {
      operationId: 'getReceivableSummary',
      method: 'get',
      path: '/receivables/summary',
      summary: 'Totals of the session branch\'s receivables; every branch for staff with access to all branches who name none',
      tag,
      responses: { 200: { description: 'The summary', schema: ReceivableSummarySchema } },
    },
    {
      operationId: 'listReceivables',
      method: 'get',
      path: '/receivables',
      summary: 'The session branch\'s receivables, newest first (?branchId= another branch needs access to all branches)',
      tag,
      request: { query: ReceivableListQuerySchema },
      responses: { 200: { description: 'One page of receivables', schema: ReceivableListResponseSchema } },
    },
    {
      operationId: 'getReceivable',
      method: 'get',
      path: '/receivables/{id}',
      summary: 'One receivable',
      tag,
      request: { params: IdParamsSchema },
      responses: receivable('The receivable'),
      errors: [400, 401, 403, 404, 500],
    },
    {
      operationId: 'collectReceivable',
      method: 'post',
      path: '/receivables/{id}/collect',
      summary: 'Record a payment: an order or POS sale through its own payment flow, an exchange difference in the ledger',
      tag,
      request: { params: IdParamsSchema, body: CollectReceivableRequestSchema },
      responses: receivable('The receivable after the payment'),
      errors: change,
    },
    {
      operationId: 'writeOffReceivable',
      method: 'post',
      path: '/receivables/{id}/write-off',
      summary: 'Close a bad debt without payment, with a reason (Admin, Manager, Finance_Officer); its sale takes no further payments',
      tag,
      request: { params: IdParamsSchema, body: WriteOffReceivableRequestSchema },
      responses: receivable('The written-off receivable'),
      errors: change,
    },
    {
      operationId: 'settleReceivable',
      method: 'post',
      path: '/receivables/{id}/settle',
      summary: 'Retired: use POST /receivables/{id}/write-off',
      tag,
      responses: {},
      errors: [401, 403, 410],
    },
    {
      operationId: 'changeReceivableDueDate',
      method: 'patch',
      path: '/receivables/{id}/due-date',
      summary: 'Set or remove the due date (Admin, Manager, Finance_Officer); the status follows the new date',
      tag,
      request: { params: IdParamsSchema, body: ReceivableDueDateRequestSchema },
      responses: receivable('The receivable'),
      errors: change,
    },
  ];
}

function paymentOperations(): ApiOperation[] {
  const tag = 'Payments';
  const roles = 'Sales, Manager, Admin, Finance_Officer';
  const otherBranch = '?branchId= another branch needs access to all branches';
  return [
    {
      operationId: 'listUnpaidOrders',
      method: 'get',
      path: '/payments/unpaid-orders',
      summary: `What customers still owe in the session branch: credit orders, POS credit sales, exchange differences (${roles}; ${otherBranch})`,
      tag,
      request: { query: UnpaidListQuerySchema },
      responses: { 200: { description: 'One page of unpaid sales', schema: UnpaidListResponseSchema } },
    },
    {
      operationId: 'createPayment',
      method: 'post',
      path: '/payments',
      summary: `Take a payment on a credit order of the session branch (${roles}); an Idempotency-Key header makes a retry return the first payment`,
      tag,
      request: { body: CreatePaymentRequestSchema },
      responses: {
        201: { description: 'The payment', schema: PaymentSchema },
        200: { description: 'The payment of an earlier request with the same Idempotency-Key', schema: PaymentSchema },
      },
      errors: [400, 401, 403, 404, 409, 422, 500],
    },
    {
      operationId: 'listPayments',
      method: 'get',
      path: '/payments',
      summary: `Payment history of the session branch: order payments and collections on POS and exchange debts, newest first (${roles}; ${otherBranch})`,
      tag,
      request: { query: PaymentListQuerySchema },
      responses: { 200: { description: 'One page of payments', schema: PaymentListResponseSchema } },
    },
    {
      operationId: 'getPayment',
      method: 'get',
      path: '/payments/{id}',
      summary: `One order payment with its refunds (${roles})`,
      tag,
      request: { params: IdParamsSchema },
      responses: { 200: { description: 'The payment', schema: PaymentSchema } },
      errors: [400, 401, 403, 404, 500],
    },
    {
      operationId: 'refundPayment',
      method: 'post',
      path: '/payments/{id}/refund',
      summary: 'Give back (part of) a payment, the way it was paid; on a credit sale the amount is owed again (Manager, Admin, Finance_Officer)',
      tag,
      request: { params: IdParamsSchema, body: RefundPaymentRequestSchema },
      responses: { 201: { description: 'The refund', schema: PaymentRefundSchema } },
      errors: [400, 401, 403, 404, 422, 500],
    },
    {
      operationId: 'listPaymentRefunds',
      method: 'get',
      path: '/payments/{id}/refunds',
      summary: `A payment's refunds (${roles})`,
      tag,
      request: { params: IdParamsSchema },
      responses: { 200: { description: 'The refunds', schema: PaymentRefundListResponseSchema } },
      errors: [400, 401, 403, 404, 500],
    },
    {
      operationId: 'listOrderPayments',
      method: 'get',
      path: '/orders/{id}/payments',
      summary: `An order's payments, oldest first (${roles})`,
      tag,
      request: { params: IdParamsSchema },
      responses: { 200: { description: 'The payments', schema: OrderPaymentListResponseSchema } },
      errors: [400, 401, 403, 404, 500],
    },
    {
      operationId: 'getOrderBalance',
      method: 'get',
      path: '/orders/{id}/balance',
      summary: `What an order has been paid and refunded, and what is still owed (${roles})`,
      tag,
      request: { params: IdParamsSchema },
      responses: { 200: { description: 'The balance', schema: OrderBalanceSchema } },
      errors: [400, 401, 403, 404, 422, 500],
    },
  ];
}
